services:
  redis:
    image: redis:latest
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 50
    restart: unless-stopped
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
