
services:
  pgadmin:
      image: dpage/pgadmin4
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      # healthcheck:
      #   test:
      #     [
      #       "CMD",
      #       "wget",
      #       "-O",
      #       "-",
      #       "http://localhost:80/misc/ping"
      #     ]
      #   interval: 10s
      #   timeout: 5s
      #   start_period: 30s
      #   retries: 3
      volumes:
        - db-data/:/var/lib/pgadmin
      ports:
        - "5050:80"
      networks:
        - database_net
